MAX_FEATURES = 250
FEATURE_OVERLAP_THRESHOLD = 0.4
VERIFICATION_CORRECT_TO_RANDOM_RATIO = 5
RETRIEVAL_CORRECT_TO_RANDOM_RATIO = 1000
MAX_NUM_RETRIEVAL_FEATURES = 10
NUM_SEQUENCES = 115
NUM_RELATED_IMAGES = 5

NUM_SAMPLE_POINTS_SCALE_CHANGE_ESTIMATION = 13

NUM_SCORES_DISTINCTIVNESS = 50
NUM_BEST_MATCHES = 50