SKIP = ["speedtest", "verification", "retrieval"]
#SKIP = ["speedtest"]
FILE_NAME = "shift_invariant_8chattern.csv"
# Rotation, scale, gaussian blur, motion blur
#NOISE_RANGES =[(-0,0), (1,1), (0,0), (0,0)]
NOISE_RANGES = [(0,0)]
FORCE_CONSTANT_ANGLE = False
KEYPOINT_SIZE_SCALINGS = [1]

MAX_FEATURES = 500
VISUALIZE = False
SEQUENCE_TO_VISUALIZE = 89

USE_DISTANCE = True
DISTANCE_THRESHOLD = 10
FEATURE_OVERLAP_THRESHOLD = 0.4
VERIFICATION_CORRECT_TO_RANDOM_RATIO = 5
RETRIEVAL_CORRECT_TO_RANDOM_RATIO = 1000
MAX_NUM_RETRIEVAL_FEATURES = 10

NUM_SEQUENCES = 115
NUM_RELATED_IMAGES = 5
NUM_ILLUMINATION_SEQUENCES = 56
NUM_ROTATION_SEQUENCES = NUM_SEQUENCES - NUM_ILLUMINATION_SEQUENCES

NUM_SAMPLE_POINTS_SCALE_CHANGE_ESTIMATION = 13
NUM_SCORES_DISTINCTIVNESS = 100
NUM_BEST_MATCHES = 100

