MAX_FEATURES = 500
FEATURE_OVERLAP_THRESHOLD = 0.3
VERIFICATION_CORRECT_TO_RANDOM_RATIO = 25
RETRIEVAL_CORRECT_TO_RANDOM_RATIO = 500
MAX_NUM_RETRIEVAL_FEATURES = 25
NUM_SEQUENCES = 116
NUM_RELATED_IMAGES = 5

NUM_SAMPLE_POINTS_SCALE_CHANGE_ESTIMATION = 50

NUM_SCORES_DISTINCTIVNESS = 10
NUM_BEST_MATCHES = 10